#ifndef _BT_HFP_H_
#define _BT_HFP_H_
#include "yc11xx.h"

#define AT_CR					0x0D
#define AT_LF					0x0A
#define AT_EOF 					0xFF

typedef enum
{
	HFP_CIND_SERVICE,
	HFP_CIND_CALL,
	HFP_CIND_CALLSETUP,
	HFP_CIND_CALLHELD,
	HFP_CIND_SIGNAL,
	HFP_CIND_ROAM,
	HFP_CIND_BATTCHG,
}HfpCINDNativeIdx;


typedef enum {
	HFP_RESULT_CODE_RING			,		//0
	HFP_RESULT_CODE_PLUS_BRSF		,
	HFP_RESULT_CODE_PLUS_CIND		,
	HFP_RESULT_CODE_PLUS_CHLD		,
	HFP_RESULT_CODE_PLUS_VGM		,
	HFP_RESULT_CODE_PLUS_VGS		,		//5
	HFP_RESULT_CODE_OK				,
	HFP_RESULT_CODE_ERROR			,					
	HFP_RESULT_CODE_CIEV			,					
	HFP_RESULT_CODE_PLUS_BVRA		,				
	HFP_RESULT_CODE_PLUS_COPS		,		//10
	HFP_RESULT_CODE_PLUS_BTRH		,				
	HFP_RESULT_CODE_PLUS_BSIR		,
	HFP_RESULT_CODE_PLUS_CNUM		,
	HFP_RESULT_CODE_PLUS_CME		,
	HFP_RESULT_CODE_PLUS_CLCC		,		//15
	HFP_RESULT_CODE_PLUS_CLIP		,
	HFP_RESULT_CODE_PLUS_CCWA		,
	HFP_RESULT_CODE_PLUS_BINP		,						
	HFP_RESULT_CODE_PLUS_XAPL		,
	HFP_RESULT_CODE_PLUS_BCS		,
}HFP_RESULT_CODE_IND;

#define HFP_RESULT_CODE_ARRAY_SIZE 20
#define HFP_RESULT_CODE_MAX_LENGTH 6

#define HFP_INDICATOR_ARRAY_SIZE			7
#define HFP_INDICATOR_MAX_LENGTH			11

void HFP_process_rfcomm_packet(uint16_t len,uint8_t *pck);
void Bt_RFCOMMCallBack(uint8_t len,uint8_t *dataPtr);
void HFP_test();
void Bt_ReportBattery();

#endif //_BT_HFP_H_
